# Generated by Django 5.1.4 on 2026-01-19 00:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(default='default_patient', max_length=255)),
                ('alert_type', models.CharField(choices=[('asthma_risk', 'Risque asthme'), ('heart_rate', 'Fréquence cardiaque'), ('temperature', 'Température'), ('respiratory', 'Respiration'), ('environment', 'Environnement'), ('info', 'Information')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyen'), ('high', 'Élevé'), ('critical', 'Critique')], max_length=20)),
                ('message', models.TextField()),
                ('sensor_data', models.JSONField(default=dict)),
                ('ai_analysis', models.JSONField(default=dict)),
                ('recommendations', models.JSONField(default=list)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='frontend_al_timesta_cb58c1_idx'), models.Index(fields=['severity'], name='frontend_al_severit_a733fd_idx'), models.Index(fields=['is_read'], name='frontend_al_is_read_3d65a4_idx')],
            },
        ),
    ]
