# Generated by Django 5.2.7 on 2025-11-10 23:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(verbose_name='Âge')),
                ('location', models.CharField(default='Paris, France', max_length=200, verbose_name='Localisation')),
                ('health_profile', models.TextField(default='Asthme chronique - Surveillance intelligente et alertes préventives personnalisées', verbose_name='Profil de santé')),
                ('connected_sensors', models.IntegerField(default=3, verbose_name='Capteurs connectés')),
                ('max_sensors', models.IntegerField(default=3, verbose_name='Capteurs maximum')),
                ('is_active', models.BooleanField(default=True, verbose_name='Surveillance active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnvironmentalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('air_quality_index', models.IntegerField(default=42, verbose_name='Indice AQI')),
                ('co2_level', models.IntegerField(default=420, verbose_name='Niveau CO₂ (ppm)')),
                ('humidity', models.IntegerField(default=55, verbose_name='Humidité (%)')),
                ('pm25', models.IntegerField(default=12, verbose_name='Particules PM2.5 (µg/m³)')),
                ('co_level', models.DecimalField(decimal_places=2, default=0.3, max_digits=5, verbose_name='CO (ppm)')),
                ('no2_level', models.IntegerField(default=18, verbose_name='NO₂ (ppb)')),
                ('o3_level', models.IntegerField(default=35, verbose_name='O₃ (ppb)')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'enregistrement")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environmental_data', to='health.patient')),
            ],
            options={
                'verbose_name': 'Donnée environnementale',
                'verbose_name_plural': 'Données environnementales',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('alert_type', models.CharField(choices=[('info', 'Information'), ('success', 'Succès'), ('warning', 'Avertissement'), ('danger', 'Danger')], default='info', max_length=20, verbose_name='Type')),
                ('level', models.CharField(choices=[('low', 'Basse'), ('medium', 'Moyenne'), ('high', 'Haute'), ('critical', 'Critique')], default='low', max_length=20, verbose_name='Niveau')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='health.patient')),
            ],
            options={
                'verbose_name': 'Alerte',
                'verbose_name_plural': 'Alertes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhysiologicalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart_rate', models.IntegerField(default=72, verbose_name='Rythme cardiaque (bpm)')),
                ('oxygen_saturation', models.DecimalField(decimal_places=2, default=98.0, max_digits=5, verbose_name='Saturation O₂ (%)')),
                ('temperature', models.DecimalField(decimal_places=1, default=36.8, max_digits=4, verbose_name='Température (°C)')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'enregistrement")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physiological_data', to='health.patient')),
            ],
            options={
                'verbose_name': 'Donnée physiologique',
                'verbose_name_plural': 'Données physiologiques',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
